// <auto-generated />
using System;
using LogMyDay.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogMyDay.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LogMyDayDbContext))]
    [Migration("20260529062329_DropReminderListAddUserId")]
    partial class DropReminderListAddUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LogMyDay.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateFinished")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateStarted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("LogMyDay_Activities", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.EventLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Level")
                        .HasDatabaseName("IX_LogMyDay_EventLogs_Level");

                    b.HasIndex("UserId", "CreatedUtc")
                        .HasDatabaseName("IX_LogMyDay_EventLogs_UserId_CreatedUtc");

                    b.ToTable("LogMyDay_EventLogs", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.EventLogDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventLogId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventLogId")
                        .IsUnique();

                    b.ToTable("LogMyDay_EventLogDetails", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.InputType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMaximumEditable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMinimumEditable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRangeEditable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRepeatableEditable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStepEditable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogMyDay_InputTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Whole number input (e.g., 1, 42, -5)",
                            IsMaximumEditable = true,
                            IsMinimumEditable = true,
                            IsRangeEditable = true,
                            IsRepeatableEditable = true,
                            IsStepEditable = true,
                            Name = "Integer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Free-form text input",
                            IsMaximumEditable = false,
                            IsMinimumEditable = false,
                            IsRangeEditable = true,
                            IsRepeatableEditable = true,
                            IsStepEditable = false,
                            Name = "String"
                        },
                        new
                        {
                            Id = 3,
                            Description = "True/false checkbox input",
                            IsMaximumEditable = false,
                            IsMinimumEditable = false,
                            IsRangeEditable = true,
                            IsRepeatableEditable = false,
                            IsStepEditable = false,
                            Name = "Boolean"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Date selection input",
                            IsMaximumEditable = false,
                            IsMinimumEditable = false,
                            IsRangeEditable = true,
                            IsRepeatableEditable = false,
                            IsStepEditable = false,
                            Name = "Date"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Time selection input",
                            IsMaximumEditable = false,
                            IsMinimumEditable = false,
                            IsRangeEditable = true,
                            IsRepeatableEditable = false,
                            IsStepEditable = false,
                            Name = "Time"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Decimal number with 2 decimal places (e.g., 3.14, 99.99)",
                            IsMaximumEditable = true,
                            IsMinimumEditable = true,
                            IsRangeEditable = true,
                            IsRepeatableEditable = true,
                            IsStepEditable = true,
                            Name = "Decimal, precision 2"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Star rating scale from 0 to 5 (higher is better)",
                            IsMaximumEditable = false,
                            IsMinimumEditable = false,
                            IsRangeEditable = true,
                            IsRepeatableEditable = false,
                            IsStepEditable = false,
                            Name = "Star Rating 0-5"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Star rating scale from 0 to 10 (higher is better)",
                            IsMaximumEditable = false,
                            IsMinimumEditable = false,
                            IsRangeEditable = true,
                            IsRepeatableEditable = false,
                            IsStepEditable = false,
                            Name = "Star Rating 0-10"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Percentage value from 0 to 100",
                            IsMaximumEditable = false,
                            IsMinimumEditable = false,
                            IsRangeEditable = true,
                            IsRepeatableEditable = false,
                            IsStepEditable = false,
                            Name = "Percentage"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Score scale from 0 to 5 (lower is better, e.g. pain, severity)",
                            IsMaximumEditable = false,
                            IsMinimumEditable = false,
                            IsRangeEditable = true,
                            IsRepeatableEditable = false,
                            IsStepEditable = false,
                            Name = "Score 0-5"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Score scale from 0 to 10 (lower is better, e.g. pain, severity)",
                            IsMaximumEditable = false,
                            IsMinimumEditable = false,
                            IsRangeEditable = true,
                            IsRepeatableEditable = false,
                            IsStepEditable = false,
                            Name = "Score 0-10"
                        });
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.PasswordReset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UsedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .HasDatabaseName("IX_LogMyDay_PasswordResets_Token");

                    b.HasIndex("UserId");

                    b.ToTable("LogMyDay_PasswordResets", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Pattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatternValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogMyDay_Patterns", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Quantity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.ToTable("LogMyDay_Quantities", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowUnfilled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoLogMode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompletionTagId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int?>("MonitorDaysBack")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("MonitorFromDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("MonitorToDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("NotifyAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecurrenceType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SkippedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletionTagId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_LogMyDay_Reminders_UserId");

                    b.ToTable("LogMyDay_Reminders", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.ScanMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeValue")
                        .HasDatabaseName("IX_LogMyDay_ScanMappings_CodeValue");

                    b.HasIndex("TagId");

                    b.HasIndex("UserId", "CodeValue")
                        .IsUnique()
                        .HasDatabaseName("IX_LogMyDay_ScanMappings_UserId_CodeValue");

                    b.ToTable("LogMyDay_ScanMappings", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_LogMyDay_Settings_Key");

                    b.ToTable("LogMyDay_Settings", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InputTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRange")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinValue")
                        .HasColumnType("REAL");

                    b.Property<int?>("OptionListId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PatternId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Step")
                        .HasColumnType("REAL");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeGranularity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("InputTypeId");

                    b.HasIndex("OptionListId");

                    b.HasIndex("PatternId");

                    b.HasIndex("UnitId");

                    b.ToTable("LogMyDay_Tags", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.TagDayLock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SetAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SetBy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("UserId", "TagId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_LogMyDay_TagDayLocks_UserId_TagId_Date");

                    b.ToTable("LogMyDay_TagDayLocks", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.TagGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_LogMyDay_TagGroups_UserId");

                    b.ToTable("LogMyDay_TagGroups", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.TagOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("OptionListId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OptionListId");

                    b.ToTable("LogMyDay_TagOptions", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.TagOptionList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogMyDay_TagOptionLists", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoLogMode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompletionTagId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("ListId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("NotifyAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecurrenceType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SkippedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletionTagId");

                    b.HasIndex("ListId");

                    b.ToTable("LogMyDay_TodoItems", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.TodoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowOnHomepage")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_LogMyDay_TodoLists_UserId");

                    b.ToTable("LogMyDay_TodoLists", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AToBase")
                        .HasColumnType("REAL");

                    b.Property<double>("BToBase")
                        .HasColumnType("REAL");

                    b.Property<int>("Decimals")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuantityId");

                    b.ToTable("LogMyDay_Units", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityDisplayType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityPeriodSort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivitySortOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_LogMyDay_Users_Email");

                    b.ToTable("LogMyDay_Users", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Activity", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.EventLog", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.EventLogDetail", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.EventLog", "EventLog")
                        .WithOne("Detail")
                        .HasForeignKey("LogMyDay.Domain.Entities.EventLogDetail", "EventLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventLog");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.PasswordReset", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Quantity", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnit");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.Tag", "CompletionTag")
                        .WithMany()
                        .HasForeignKey("CompletionTagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CompletionTag");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.ScanMapping", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Tag", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.TagGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogMyDay.Domain.Entities.InputType", "InputType")
                        .WithMany()
                        .HasForeignKey("InputTypeId");

                    b.HasOne("LogMyDay.Domain.Entities.TagOptionList", "OptionList")
                        .WithMany()
                        .HasForeignKey("OptionListId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogMyDay.Domain.Entities.Pattern", "Pattern")
                        .WithMany()
                        .HasForeignKey("PatternId");

                    b.HasOne("LogMyDay.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");

                    b.Navigation("InputType");

                    b.Navigation("OptionList");

                    b.Navigation("Pattern");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.TagDayLock", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.TagOption", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.TagOptionList", "OptionList")
                        .WithMany("Options")
                        .HasForeignKey("OptionListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionList");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.TodoItem", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.Tag", "CompletionTag")
                        .WithMany()
                        .HasForeignKey("CompletionTagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogMyDay.Domain.Entities.TodoList", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletionTag");

                    b.Navigation("List");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Unit", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.Quantity", "Quantity")
                        .WithMany()
                        .HasForeignKey("QuantityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quantity");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.EventLog", b =>
                {
                    b.Navigation("Detail");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.TagOptionList", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.TodoList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
