// <auto-generated />
using System;
using LogMyDay.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogMyDay.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LogMyDayDbContext))]
    [Migration("20260206164205_AddAppSettings")]
    partial class AddAppSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogMyDay.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFinished")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStarted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("LogMyDay_Activities", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_LogMyDay_Settings_Key");

                    b.ToTable("LogMyDay_Settings", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.InputType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMaximumEditable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMinimumEditable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRangeEditable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRepeatableEditable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStepEditable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogMyDay_InputTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Whole number input (e.g., 1, 42, -5)",
                            IsMaximumEditable = true,
                            IsMinimumEditable = true,
                            IsRangeEditable = true,
                            IsRepeatableEditable = true,
                            IsStepEditable = true,
                            Name = "Integer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Free-form text input",
                            IsMaximumEditable = false,
                            IsMinimumEditable = false,
                            IsRangeEditable = true,
                            IsRepeatableEditable = false,
                            IsStepEditable = false,
                            Name = "String"
                        },
                        new
                        {
                            Id = 3,
                            Description = "True/false checkbox input",
                            IsMaximumEditable = false,
                            IsMinimumEditable = false,
                            IsRangeEditable = true,
                            IsRepeatableEditable = false,
                            IsStepEditable = false,
                            Name = "Boolean"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Date selection input",
                            IsMaximumEditable = false,
                            IsMinimumEditable = false,
                            IsRangeEditable = true,
                            IsRepeatableEditable = false,
                            IsStepEditable = false,
                            Name = "Date"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Time selection input",
                            IsMaximumEditable = false,
                            IsMinimumEditable = false,
                            IsRangeEditable = true,
                            IsRepeatableEditable = false,
                            IsStepEditable = false,
                            Name = "Time"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Decimal number with 2 decimal places (e.g., 3.14, 99.99)",
                            IsMaximumEditable = true,
                            IsMinimumEditable = true,
                            IsRangeEditable = true,
                            IsRepeatableEditable = true,
                            IsStepEditable = true,
                            Name = "Decimal, precision 2"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Rating scale from 1 to 5 (commonly used for star ratings)",
                            IsMaximumEditable = false,
                            IsMinimumEditable = false,
                            IsRangeEditable = true,
                            IsRepeatableEditable = false,
                            IsStepEditable = false,
                            Name = "Rating 1-5"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Rating scale from 1 to 10",
                            IsMaximumEditable = false,
                            IsMinimumEditable = false,
                            IsRangeEditable = true,
                            IsRepeatableEditable = false,
                            IsStepEditable = false,
                            Name = "Rating 1-10"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Percentage value from 0 to 100",
                            IsMaximumEditable = false,
                            IsMinimumEditable = false,
                            IsRangeEditable = true,
                            IsRepeatableEditable = false,
                            IsStepEditable = false,
                            Name = "Percentage"
                        });
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.PasswordReset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UsedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .HasDatabaseName("IX_LogMyDay_PasswordResets_Token");

                    b.HasIndex("UserId");

                    b.ToTable("LogMyDay_PasswordResets", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Pattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatternValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogMyDay_Patterns", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Quantity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.ToTable("LogMyDay_Quantities", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InputTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRange")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("float");

                    b.Property<double?>("MinValue")
                        .HasColumnType("float");

                    b.Property<int?>("OptionListId")
                        .HasColumnType("int");

                    b.Property<int?>("PatternId")
                        .HasColumnType("int");

                    b.Property<double?>("Step")
                        .HasColumnType("float");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeGranularity")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InputTypeId");

                    b.HasIndex("OptionListId");

                    b.HasIndex("PatternId");

                    b.HasIndex("UnitId");

                    b.ToTable("LogMyDay_Tags", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.TagOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OptionListId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OptionListId");

                    b.ToTable("LogMyDay_TagOptions", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.TagOptionList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("LogMyDay_TagOptionLists", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AToBase")
                        .HasColumnType("float");

                    b.Property<double>("BToBase")
                        .HasColumnType("float");

                    b.Property<int>("Decimals")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityId")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuantityId");

                    b.ToTable("LogMyDay_Units", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_LogMyDay_Users_Email");

                    b.ToTable("LogMyDay_Users", (string)null);
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Activity", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.PasswordReset", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Quantity", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnit");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Tag", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.InputType", "InputType")
                        .WithMany()
                        .HasForeignKey("InputTypeId");

                    b.HasOne("LogMyDay.Domain.Entities.TagOptionList", "OptionList")
                        .WithMany()
                        .HasForeignKey("OptionListId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogMyDay.Domain.Entities.Pattern", "Pattern")
                        .WithMany()
                        .HasForeignKey("PatternId");

                    b.HasOne("LogMyDay.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InputType");

                    b.Navigation("OptionList");

                    b.Navigation("Pattern");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.TagOption", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.TagOptionList", "OptionList")
                        .WithMany("Options")
                        .HasForeignKey("OptionListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionList");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Unit", b =>
                {
                    b.HasOne("LogMyDay.Domain.Entities.Quantity", "Quantity")
                        .WithMany()
                        .HasForeignKey("QuantityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quantity");
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.Tag", b =>
                {
                });

            modelBuilder.Entity("LogMyDay.Domain.Entities.TagOptionList", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
